In [1]:
!pip install numpy 

In [2]:
import numpy as np

In [28]:
a=np.random.rand(2,3,4)
a

array([[[0.45072012, 0.54058543, 0.30796897, 0.09556086],
        [0.43139806, 0.78632926, 0.73262096, 0.13142455],
        [0.25936856, 0.46287032, 0.61387263, 0.49683404]],

       [[0.52273548, 0.6408877 , 0.1055807 , 0.16219679],
        [0.81338084, 0.98395731, 0.45309857, 0.13301459],
        [0.55295121, 0.47263311, 0.80174915, 0.37828384]]])

In [5]:
a.shape

(2, 3, 4)

In [6]:
type(a)

numpy.ndarray

In [8]:
b=np.zeros((2,2,2))
b

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
c=np.ones((3,3,3))
c

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
d=np.arange(9)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
d.shape

(9,)

In [15]:
d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
d.shape

(9,)

In [17]:
lst1=np.random.rand(10)
lst2=np.random.rand(10)

In [19]:
lst1

array([0.50668532, 0.82572617, 0.63849331, 0.67415895, 0.78665017,
       0.78355203, 0.38613905, 0.62898749, 0.63517632, 0.8303473 ])

In [20]:
lst2

array([0.62578186, 0.04370429, 0.9833743 , 0.86024754, 0.69854627,
       0.23980017, 0.63502376, 0.81089457, 0.55841094, 0.4624828 ])

In [21]:
add=np.add(lst1,lst2)
add


array([1.13246718, 0.86943047, 1.62186761, 1.53440649, 1.48519644,
       1.02335221, 1.0211628 , 1.43988206, 1.19358727, 1.2928301 ])

In [23]:
sub=np.subtract(lst1,lst2)
sub

array([-0.11909654,  0.78202188, -0.34488099, -0.18608859,  0.0881039 ,
        0.54375186, -0.24888471, -0.18190708,  0.07676538,  0.36786451])

In [24]:
mul=np.multiply(lst1,lst2)
mul

array([0.31707448, 0.03608778, 0.62787791, 0.57994358, 0.54951154,
       0.18789591, 0.24520747, 0.51004254, 0.35468941, 0.38402134])

In [25]:
div=np.divide(lst1,lst2)
div

array([ 0.80968362, 18.89347941,  0.64928818,  0.78368018,  1.12612465,
        3.26752071,  0.60807024,  0.77567111,  1.13747113,  1.7954123 ])

In [26]:
dot=np.dot(lst1,lst2)
dot

3.7923519648561603

In [27]:
div.sort()
div

array([ 0.60807024,  0.64928818,  0.77567111,  0.78368018,  0.80968362,
        1.12612465,  1.13747113,  1.7954123 ,  3.26752071, 18.89347941])

In [29]:
#Create a null vector of size 10 but the fifth value which is 1
vec=np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
vec[4]=1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [32]:
#Create a vector with values ranging from 10 to 49
#Reverse a vector (first element becomes last)
elt=np.arange(10,50)
elt

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [33]:
elt=np.arange(20)
elt

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
elt=elt[::-1]
elt

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [35]:
elt=np.arange(10,50)
print(elt)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [41]:
#Create a 3x3 matrix with values ranging from 0 to 8
apt=np.arange(9).reshape(3,3)
apt

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])