In [2]:
import numpy as np

In [3]:
a=np.random.rand(2,3,5)
a

array([[[0.62071072, 0.96858094, 0.46494862, 0.42266268, 0.2933335 ],
        [0.47131593, 0.10626621, 0.48796933, 0.12939504, 0.49863579],
        [0.88181668, 0.34039886, 0.15145081, 0.60861122, 0.66653208]],

       [[0.55182786, 0.29862725, 0.42027112, 0.8107835 , 0.61049119],
        [0.62483192, 0.75969299, 0.86960134, 0.14646796, 0.76905176],
        [0.607387  , 0.44623454, 0.24136845, 0.9700659 , 0.1751098 ]]])

In [4]:
type(a)

numpy.ndarray

In [5]:
vec=np.arange(10,51)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
vec[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

In [10]:
b=np.zeros((10))
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
b.shape


(10,)

In [16]:
b.reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
lst1=np.arange(10,20)
lst2=np.arange(30,40)


In [23]:
add=np.add(lst1,lst2)
add

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [24]:
add.reshape(2,5)

array([[40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [25]:
elt=np.dot(lst1,lst2)
elt

5085